[config]
version_check = false

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi/rofi-colors.rasi"
output_path = "~/.config/rofi/themes/colors.rasi"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar/colors.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = "hyprctl reload"

[templates.wezterm]
input_path = "~/.config/matugen/templates/wezterm/wezterm_theme.toml"
output_path = "~/.config/wezterm/colors/matugen_theme.toml"
post_hook = "touch ~/.config/wezterm/wezterm.lua"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell/colors.json"
output_path = "~/.local/state/quickshell/generated/colors.json"

[templates.obsidian]
input_path = "~/.config/matugen/templates/obsidian.css"
output_path = "~/vaults/notes/.obsidian/snippets/matugen.css"
