hl.on("hyprland.start", function()
    hl.exec_cmd(Apps.Terminal)
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("hyprpm reload -n")
end)
